### ISSUE TITLE
Subsequent results generating mess

### ISSUE THREAD

**Issue by eSlider** [mattcurf/ollama-intel-gpu#4]
Initially the first prompt works fine, inference gives wonderful results, but subsequent results generate mess.

By trial and error, or rather I wrote a script that directly calls ollama, I found out that as long as the prefix of the prompt coincides with the previous one, the results are good, but with new prompts a mess is generated and it can only be cured by overloading the model in memory by changing the batch_size through the interface, for example, or if you directly request the model, specify its lifetime in memory.

I identified this problem on three different machines with the same GPU's: ARC A770M and 12th generation CPU.
In total I tested on 6 separate GPUs - the result is the same everywhere.
Changing the use of the specified environment variables in Dockerfile or via docker-compose environment variables did not affect the result.
I would also add that I tested on all current versions of llama 3b/8b; instruct/v2, v3.1 v3.2 and also gwen. 

I would like to understand:
- Am I the only one with this problem, but on three different machines?
- What are some solutions, besides reloading the model at each new prompt(~3s) 

> I want to express special thanks for the posted code, as it is a pain to collect all these dependencies, which cost me many sleepless nights and I bow my knee to the creator. Thank you, @mattcurf!

**Comment by mattcurf** [comment]
Fixed with #6
