### ISSUE TITLE
Add a prebuilt image?

### ISSUE THREAD

**Issue by dbirks** [mattcurf/ollama-intel-gpu#7]
Hey thanks for putting this project together. I just got a new laptop with an Arc integrated gpu, and went searching for a way to get ollama to use it. It's nice to see `intel_gpu_top` showing activity on my gpu now :) 

Would you like if I submitted a PR to add github actions to pre-build the image from the Dockerfile, just so it's a little quicker for people to get up-and-running here? The image would push to Github Container Registry, so no need to set up separate creds for a Docker Hub account or something. 

I've got it just about working in my fork, you can see what the images look like in Github Container Registry (like a subset of Github Packages I believe):
https://github.com/dbirks/ollama-intel-gpu/pkgs/container/ollama-intel-gpu

**Comment by mattcurf** [comment]
That would be great! 😀

**Comment by watn3y** [comment]
Keep in mind that Github limits CI/CD minutes and Storage used for free Tier users. Since this image is relatively heavy to build and not the smallest(@dbirks's latest build is 8,5GB compressed) you might bump into a limit somewhere :)

**Comment by mattcurf** [comment]
Resolved with https://github.com/mattcurf/ollama-intel-gpu/pull/11
