### ISSUE TITLE
fix dockerfile and general info

### ISSUE THREAD

**Issue by Malaga82** [mattcurf/ollama-intel-gpu#9]
Hello,
in dockerfile:

https://github.com/oneapi-src/level-zero/releases/download/v1.18.3/level-zero_1.18.3+u22.04_amd64.deb

is missing, the new link is:

https://github.com/oneapi-src/level-zero/releases/download/v1.18.5/level-zero_1.18.5+u22.04_amd64.deb

BTW what should be GPU tokens/s?
For example i have near 8 tks/s with hf.co/MaziyarPanahi/Qwen2.5-7B-Instruct-GGUF:Q4_K_M  on ultra 7 155H with integrated arc, i don't know if it's good or not.
You could add some tests just for reference :)
Thanks

**Comment by mattcurf** [comment]
Ugh, Intel should never remove old links.  Thanks for the notice.

**Comment by mattcurf** [comment]
See https://github.com/mattcurf/ollama-intel-gpu/pull/11 for an alternative fix for this
